### ISSUE TITLE
Files Missing or Something?

### ISSUE THREAD

**Issue by usman-combinaryclix** [Basscord/video-chat#1]
Hi I tried to clone your repository and also executed the npm install. And moved the files in public folder to root folder. 
I think socket.io folder is missing or the path? Can you please explain a little how can I use your demo to work on my local server.

I am using XAMPP + PHP for my application!

**Comment by Basscord** [comment]
Hi @usman-combinaryclix here's the steps to get up and running:

1. `git clone https://github.com/Basscord/video-chat.git`
2. `npm install`
3. `npm start`
4. Navigate a browser window to localhost:3000
5. Navigate a 2nd browser window to localhost:3000

The project is written in Javascript, and doesn't use XAMPP, PHP, or Apache. There's no need to move any files into a directory served by Apache. The project should run in any directory, as is.

Socket.io will be found within the project root `node_modules` directory, which is created after you run `npm install`.

The only gotcha is, once you get up and running, most browsers require HTTPS to use the camera & microphone anywhere besides `localhost`, so if you want to run this app in a serious manner, you'll want to learn about deploying Node.js apps to an HTTPS environment.

Let me know if you need anything further. Thanks!

**Comment by mcastilloz** [comment]
Hello Brian,
I like it very much your application, I replicate into my server
But some mobiles does’nt to connect, I believe is a problem of stun server, do you recommender one?

**Comment by Basscord** [comment]
Hi,

Some people are using http://numb.viagenie.ca as a quick and easy way to set up a STUN server. You can try that, or you can look into deploying a [CoTURN](https://www.webrtc-experiment.com/docs/TURN-server-installation-guide.html#coturn) server.

Best of luck!
